--------------------------------------------------------
--  파일이 생성됨 - 수요일-5월-01-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table NOTICE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."NOTICE" 
   (	"NO" NUMBER(*,0), 
	"TITLE" VARCHAR2(100 BYTE), 
	"CONTENT" VARCHAR2(1000 BYTE), 
	"RESDATE" VARCHAR2(100 BYTE), 
	"VISITED" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.NOTICE
SET DEFINE OFF;
Insert into SYSTEM.NOTICE (NO,TITLE,CONTENT,RESDATE,VISITED) values (85,'더미 제목1','더미 내용1','24/04/12',0);
Insert into SYSTEM.NOTICE (NO,TITLE,CONTENT,RESDATE,VISITED) values (86,'더미 제목2','더미 내용2','24/04/12',null);
--------------------------------------------------------
--  DDL for Index SYS_C008408
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008408" ON "SYSTEM"."NOTICE" ("NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table NOTICE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."NOTICE" ADD PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
